POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": ".NET Core Code Coverage as a Global Tool with coverlet",
  "author": "Scott Hanselman",
  "url": "https://www.hanselman.com/blog/NETCoreCodeCoverageAsAGlobalToolWithCoverlet.aspx",
  "likes": 1
}
